### PR TITLE
Assignment fixes

### LINKED ISSUE #7: Setting up Smartcar
**The team shall set up a smartcar**

### PR DESCRIPTION
**Pull request by bassamEldesouki**

### CODE REVIEW

**Review by platisd — APPROVED** [review]
looks good to me but you'll need to resolve the merge conflicts

**Comment by bassamEldesouki** [comment]
Okay, will do thanks :)

**Comment by platisd** [comment]
Avoid working on a forked repo and create pull requests from there unless you make CI run on `pull_request` too. (it's unnecessary anyway since you all have access to the repo and can create local branches)

**Comment by alrapal** [comment]
The thing is that we did not want to work with the assignment since we had more advanced code. So merging to the master is not something we want to do. (If that is what you mean by forking)

**Comment by platisd** [comment]
@alrapal no, that's not what forking is 😛
I don't know where this more advance code is but you could still have created a local branch, done the assignment, have the CI verify it and not merge it.

**Comment by alrapal** [comment]
Ok! I see.
So if I understand correctly:
- Create a local branch from the remote master
- Make changes on that local branch
- When done, make a merge request between local branch and master.
If this is correct, is it possible to do the following:


Since we have been working in pairs.

- Create a local branch from the remote master
- Make changes on that local branch
- Push the changes to a remote branch of that local branch so that colleagues can have the changes and continue working on it
- When done, make a merge request between remote branch and master?

**Comment by platisd** [comment]
> * Create a local branch from the remote master
> * Make changes on that local branch
> * Push the changes to a remote branch of that local branch so that colleagues can have the changes and continue working on it
> * When done, make a merge request between remote branch and master?

This should be your default way of working, yes.

**Comment by bassamEldesouki** [comment]
@platisd I just thought that it's also protected like your smartcar shield repository so I forked it first :)

**Comment by platisd** [comment]
The `master` branch here is indeed protected so you cannot push to it directly. You need to create a pull request and get it reviewed before being allowed to merge.
The difference is that unlike the smartcar_shield repo, here you actually have access to create your own remote branches and of course merge pull requests.

**Comment by bassamEldesouki** [comment]
Yeah right, thanks :)

**Comment by alrapal** [comment]
> This should be your default way of working, yes.

Ok, that is what we have been doing so far, but it is good to have confirmation!
Have a nice Sunday!

**Pull request merged**
