### PR TITLE
Measure traveled distance

### LINKED ISSUE #60: Odometer for the vehicle
## User Story
As a driver, I would like to be able to see the traveled distance during a trip in the app so that I can keep an eye on the distance I drove.
***
## Acceptance Criteria
8.1 The traveled mileage needs to be shown accurate.
8.2 Unit of the traveled distance is going to be in meter.
8.3 The odometer should go back to 0 between each trip.

### PR DESCRIPTION
**Pull request by bassamEldesouki**
Traveled distance is implemented and can now be seen on the UI as unit(meter) with 3 decimals.

resolves  #60
closes  #60 

Co-authored-by: @edizgenc2021 <gusgened@student.gu.se>

### CODE REVIEW

**Review by alrapal — CHANGES_REQUESTED** [review]
Hey guys!
It seems to be good on the code part, I tested it and it does seem to work.

I have a couple questions though.
I see that the distance is divided by 1000 on line 216. Since the odometers are already giving the distance in meter, wouldn't it be better to keep the value we get from the odometers ?

Also, but more for our knowledge, I noticed the odometer value is an average rounded to the upper value of both odometers.Did not notice that before. Not useful but still worth to be shared! 😄 
Capture d’écran 2021-05-07 à 18 44 47

**Comment by bassamEldesouki** [comment]
Hi Alex, the odometer returns the traveled distance in centimeters not in meters as it's documented in smartcar shield library so we have to divide on 1000 to convert to meters and also to match what is written in the user story :) 

Edit: however we have calculated wrong and that shows how good we are in math ;P hahaha. We should divide on 100 not 1000. 

Screenshot 2021-05-07 at 19 26 38

**Review by iachella — APPROVED** [review]
The code looks good, I just need a clarification:

The method "messageArrived()" (line 157) is a bit unclear for me, is its purpose similar to a "switch" between topics which aren't related to user input? So we're going to expand in this only when adding a new topic of this kind?

**Comment by alrapal** [comment]
> Hi Alex, the odometer returns the traveled distance in centimeters not in meters as it's documented in smartcar shield library so we have to divide on 1000 to convert to meters and also to match what is written in the user story :)

Ok I see !
I got confused because the emulator is showing the measurement in meters directly!

I looked at their documentation and there is no mention of the unit being changed unlike the sensors for instance. 
I will create an issue on their Git to lift this up. 

thanks for your explanation ! 

(And yeah, I could not relate the 1000 to any unit conversion that would make sense, so it was not useless to ask haha! Good you caught that up 😄 )

**Review by alrapal — APPROVED** [review]

**Comment by bassamEldesouki** [comment]
Hi Gimmy, 
messageArrived() method handles the messages that the car publishes on some specific topics. We do subscribe for these different topics in "onSuccess()" method line 128 and then handle these messages in messageArrived() method. This method is very similar to the MQTTmessageInput() in our smartcar sketch which handles the messages we need to send to the car and received from outside. 
So in messageArrived() method, we say in case of receiving a message from the car that is published on this specific topic then use these data to do this action.  In our case right now we have 3 conditions in use,  "/smartcar/camera" topic for camera stream , "/smartcar/odometer" for the traveled distance, otherwise if any other topic then print it out to the log. 
So this method can be refactored if we have more cases. It could even be refactored now if we want.  
That's how I understand it :)

**Comment by ediz-genc** [comment]
> The code looks good, I just need a clarification:
> 
> The method "messageArrived()" (line 157) is a bit unclear for me, is its purpose similar to a "switch" between topics that aren't related to user input? So we're going to expand in this only when adding a new topic of this kind?

Btw, that was a good point that you ask about the method, Gianmarco. That made us realized that we didn't add related documentation about'em. We will now shortly add the right documentation so that everyone gets a clear understanding of them.

**Pull request merged**
