### PR TITLE
Unit_Test

### LINKED ISSUE #53: [CI] Setting-up Android_CI_test framework
**Description**
The Android_CI test is going to be implemented for the UI so that all the new code snippets we are introducing to the system are implemented faultless.

**To-Do**
53.1 Android_CI test should be executed for each new push.
53.2 Android_CI should regardless return the result of the test each time when the new codes pushed.

### PR DESCRIPTION
**Pull request by ediz-genc**
Unit test command lines in GUI_CI.yml added to test our code on the Linux system.

Resolves #53
Closes #53 

Co-authored-by: @bassamEldesouki <bassam.eldesouki.k@gmail.com>

### CODE REVIEW

**Review by platisd — COMMENTED** [review]
Does that mean you are planning to add unit tests? :tada:

**Comment by bassamEldesouki** [comment]
> Does that mean you are planning to add unit tests? 🎉

@platisd yes :) we are working on it, it will be the next Issue to add for this (CI_Implementation) Milestone :)

**Review by alrapal — APPROVED** [review]
Will be nice to also test the code, not just build it 🧪 
You will have to explain exactly what it does though 😆 and more importantly, how we can implement the tests (if they are not automatically done with gradle, totally new to that.) 
Otherwise, the code seems good based on what I know on CI 😄

**Comment by ediz-genc** [comment]
> Will be nice to also test the code, not just build it 🧪
> You will have to explain exactly what it does though 😆 and more importantly, how we can implement the tests (if they are not automatically done with gradle, totally new to that.)
> Otherwise, the code seems good based on what I know on CI 😄

Well, the testing part is not done yet and it takes time since it is new to us as well. We still need to implement the testing units. I believe Bassam mentioned earlier. Explaining the implementation can't be done here so it is better we explain what we understood about it so far in the next meeting :)

**Comment by alrapal** [comment]
> Well, the testing part is not done yet and it takes time since it is new to us as well. We still need to implement the testing units. I believe Bassam mentioned earlier. Explaining the implementation can't be done here so it is better we explain what we understood about it so far in the next meeting :)

Sounds good! 😊

**Review by iachella — APPROVED** [review]
Nice one about the testing :)
The code looks good 👍

**Pull request merged**
