### PR TITLE
Thumbstick, Speedbar, and Speedometer

### LINKED ISSUE #42: Thumbstick Control
Description:
As a driver, I want to be able to move the car via thumbstick so I may traverse to the angle/ direction I choose..

Acceptance criteria:
The car drives in the direction pointed by the joystick.
The car adjusts speed depending on the joystick's deviation from its origin.

### LINKED ISSUE #43: Manual speed setting
**Description:**
As a driver, I want to be able to accurately specify the vehicle's speed, so that I have a better control over speed related functionalities.

**Acceptance criteria:**
- The driver can specify the vehicle's speed via the app interface
- The specified speed will be updated and displayed on the interface

### PR DESCRIPTION
**Pull request by juliavankirk**
Contributors: @juliavankirk @iachella 

Resolves #42 The app now features a Thumbstick instead of a D-Pad.  This controls both speed and direction of the vehicle, and should automatically stop the car when the thumbstick is released.

Resolves #43 The Speedbar is implemented for cruise control and speed-limit functionalities later on.

The Speedometer should show at which speed the vehicle is driving.

### CODE REVIEW

**Comment by alrapal** [comment]
I will have a look at this later this afternoon if that is okay? 😊

**Comment by alrapal** [comment]
The CI caught this:

> Errors found:
 
 > /home/runner/work/group-07/group-07/UI/app/src/main/res/layout/activity_dashboard.xml:92: Error: Corresponding method handler 'public void setSpeed(android.view.View)' not found [OnClick]
              android:onClick="setSpeed"/>
              
I think it has to do with the seekbar, the setSpeed method does not seem to be created in the java code :).

**Comment by ChrisAxt** [comment]
I couldn't test this as there seems to be something stopping the car from moving according to the input from the joystick. There is information being sent and received but no reaction from the car.

**Comment by ChrisAxt** [comment]
Tested it on my laptop without issue (Worked perfectly) then tried it on my PC and there was quite a big delay between input and the car responding. I'm not sure why there would be a difference but I did double check everything and couldn't find any differences between the way it was run on the two machines.

**Review by alrapal — APPROVED** [review]
Works for me!
I tried it and it is pretty smooth. Integrates well with the car behaviours.
I see that you took away the commented code from the first version and fixed the CI errors. 

Good job 😄 

[EDIT: I tested the UI with the latest SmartCar version from the master]

**Pull request merged**
